In [1]:
import os
import sys

if os.path.basename(os.getcwd()) == "testing":
    os.chdir(os.path.dirname(os.getcwd()))
    sys.path.append(os.getcwd())

from lossless.component.core.arm_image import MultiImageArmDescriptor

descriptor = MultiImageArmDescriptor()

In [2]:
descriptor.set_image_size((16, 17)) # height, width
# print(descriptor)

In [3]:
descriptor.simple_grid_routing(4, 8)
print(descriptor.routing_grid.numpy())

[[ 0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7]
 [ 0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7]
 [ 0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7]
 [ 0  0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7]
 [ 8  8  8  9  9 10 10 11 11 12 12 13 13 14 14 15 15]
 [ 8  8  8  9  9 10 10 11 11 12 12 13 13 14 14 15 15]
 [ 8  8  8  9  9 10 10 11 11 12 12 13 13 14 14 15 15]
 [ 8  8  8  9  9 10 10 11 11 12 12 13 13 14 14 15 15]
 [16 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23]
 [16 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23]
 [16 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23]
 [16 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23]
 [24 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31]
 [24 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31]
 [24 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31]
 [24 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31]]


In [4]:
print(*descriptor.expert_indices, sep="\n")

tensor([ 0,  1,  2, 17, 18, 19, 34, 35, 36, 51, 52, 53])
tensor([ 3,  4, 20, 21, 37, 38, 54, 55])
tensor([ 5,  6, 22, 23, 39, 40, 56, 57])
tensor([ 7,  8, 24, 25, 41, 42, 58, 59])
tensor([ 9, 10, 26, 27, 43, 44, 60, 61])
tensor([11, 12, 28, 29, 45, 46, 62, 63])
tensor([13, 14, 30, 31, 47, 48, 64, 65])
tensor([15, 16, 32, 33, 49, 50, 66, 67])
tensor([ 68,  69,  70,  85,  86,  87, 102, 103, 104, 119, 120, 121])
tensor([ 71,  72,  88,  89, 105, 106, 122, 123])
tensor([ 73,  74,  90,  91, 107, 108, 124, 125])
tensor([ 75,  76,  92,  93, 109, 110, 126, 127])
tensor([ 77,  78,  94,  95, 111, 112, 128, 129])
tensor([ 79,  80,  96,  97, 113, 114, 130, 131])
tensor([ 81,  82,  98,  99, 115, 116, 132, 133])
tensor([ 83,  84, 100, 101, 117, 118, 134, 135])
tensor([136, 137, 138, 153, 154, 155, 170, 171, 172, 187, 188, 189])
tensor([139, 140, 156, 157, 173, 174, 190, 191])
tensor([141, 142, 158, 159, 175, 176, 192, 193])
tensor([143, 144, 160, 161, 177, 178, 194, 195])
tensor([145, 146, 162, 163, 

In [ ]:
import torch

models = torch.nn.ModuleList(
    torch.nn.ModuleList(
        torch.nn.Linear(10, 20) for _ in range(4)
    ) for _ in range(2)
)

Linear(in_features=10, out_features=20, bias=True)


In [14]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = [0,1,2,3]
b[int(a[0,0].item())]

1